name: pytorch-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - captum
  - cudatoolkit=11.1
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.9
  - python-language-server
  - pytorch=1.9
  - pytorch-lightning
  - pyviz_comms
  - scikit-learn
  - scipy
  - tensorboard
  - torchaudio
  - torchmetrics
  - torchtext
  - torchvision
  - wandb
  - xeus-python
