name: scikit-learn-env

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - dask
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.10
  - python-language-server
  - pyviz_comms
  - scikit-learn
  - scipy
  - wandb
  - xeus-python
